[network]
ip_address = "127.0.0.1:8000"

[monitor_groups]
OT = 0
Group3_4 = 2
Resten = 4

[aux_channels]
OT_AB = 0
OT_CD = 2
H90 = 4
Space = 6
Modular = 8

[channels]
H90 = 0
OT = 2
Wavestate = 4
Space = 6
Super6 = 8
WhatYouHear = 10
Mod_3_4 = 22
AR_Rimshot = 30
Pro1 = 31
Syntakt = 32
AR_Kick = 34
AR_Snare = 35
PolyD = 36
Mod_M1 = 42
Mod_M2 = 43
Mod_M3 = 44
Mod_M4 = 45
Mod_1_2 = 46


