[network]
ip_address = "127.0.0.1:8000"

[monitor_groups]
0 = "OT"
2 = "Group3_4"
4 = "Resten"

[aux_channels]
0 = "OT_AB"
2 = "OT_CD"
4 = "H90"
6 = "Space"
8 = "Modular"

[channels]
0 = "H90"
2 = "OT"
4 = "Wavestate"
6 = "Space"
8 = "Super6"
10 = "WhatYouHear"
22 = "Mod_3_4"
30 = "AR_Rimshot"
31 = "Pro1"
32 = "Syntakt"
34 = "AR_Kick"
35 = "AR_Snare"
36 = "PolyD"
42 = "Mod_M1"
43 = "Mod_M2"
44 = "Mod_M3"
45 = "Mod_M4"
46 = "Mod_1_2"

[midi_config]
input = "MIDIIN2 (Arturia KeyStep 32)"
output = "MIDIOUT2 (Arturia KeyStep 32)"
midi_channel = 1

[midi_mapping_cc]
34 = "vol(2)"
35 = "vol(4)"
74 = "send(2,4)"
88 = "init"
89 = "monitor_on"
90 = "monitor_off"