[network]
ip_address = "127.0.0.1:8000"

[monitor_groups]
0 = "OT"
2 = "Group3_4"
4 = "Resten"

[aux_channels]
0 = "OT_AB"
2 = "OT_CD"
4 = "H90"
6 = "Space"
8 = "Modular"

[channels]
0 = "H90"
2 = "OT"
4 = "Wavestate"
6 = "Space"
8 = "Super6"
10 = "WhatYouHear"
22 = "Mod_3_4"
30 = "AR_Rimshot"
31 = "Pro1"
32 = "Syntakt"
34 = "AR_Kick"
35 = "AR_Snare"
36 = "PolyD"
42 = "Mod_M1"
43 = "Mod_M2"
44 = "Mod_M3"
45 = "Mod_M4"
46 = "Mod_1_2"

[midi_config]
input = "MIDIIN2 (Arturia KeyStep 32)"
output = "MIDIOUT2 (Arturia KeyStep 32)"
midi_channel = 5

# [midi_mapping_cc]
# 34 = "vol(2)"
# 35 = "vol(4)"
# 74 = "send(2,4)"
# 88 = "init"
# 89 = "monitor_on"
# 90 = "monitor_off"

[midi_mapping_cc]
1 = "send(31,4)"
2 = "send(36,4)"
3 = "send(8,4)"
4 = "send(46,4)"
5 = "send(22,4)"
6 = "send(42,4)"
7 = "send(4,4)"
8 = "send(43,4)"
9 = "send(6,4)"
10 = "send(2,4)"
11 = "send(0,4)"
12 = "send(10,4)"
13 = "send(31,8)"
14 = "send(36,8)"
15 = "send(8,8)"
16 = "send(46,8)"
17 = "send(22,8)"
18 = "send(42,8)"
19 = "send(4,8)"
20 = "send(43,8)"
21 = "send(6,8)"
22 = "send(2,8)"
23 = "send(0,8)"
24 = "send(10,8)"
25 = "vol(31)"
26 = "vol(36)"
27 = "vol(8)"
28 = "vol(46)"
29 = "vol(22)"
30 = "vol(42)"
31 = "vol(4)"
32 = "vol(43)"
33 = "vol(6)"
34 = "vol(2)"
35 = "vol(0)"
36 = "vol(10)"
37 = "send(31,0)"
38 = "send(36,0)"
39 = "send(8,0)"
40 = "send(46,0)"
41 = "send(22,0)"
42 = "send(42,0)"
43 = "send(4,0)"
44 = "send(43,0)"
45 = "send(6,0)"
46 = "send(2,0)"
47 = "send(0,0)"
48 = "send(10,0)"
49 = "send(31,2)"
50 = "send(36,2)"
51 = "send(8,2)"
52 = "send(46,2)"
53 = "send(22,2)"
54 = "send(42,2)"
55 = "send(4,2)"
56 = "send(43,2)"
57 = "send(6,2)"
58 = "send(2,2)"
59 = "send(0,2)"
60 = "send(10,2)"
66 = "send(31,6)"
67 = "send(36,6)"
68 = "send(8,6)"
69 = "send(46,6)"
70 = "send(22,6)"
71 = "send(42,6)"
72 = "send(4,6)"
73 = "send(43,6)"
74 = "send(6,6)"
75 = "send(2,6)"
76 = "send(0,6)"
77 = "send(10,6)"
# 80 = "/mix/aux/4)"

[midi_mapping_note_on]
21 = "send(31,0)"
22 = "send(36,0)"
23 = "send(8,0)"
24 = "send(46,0)"
25 = "send(31,2)"
26 = "send(36,2)"
27 = "send(8,2)"
28 = "send(46,2)"
31 = "send(22,0)"
32 = "send(42,0)"
33 = "send(4,0)"
34 = "send(43,0)"
35 = "send(22,2)"
36 = "send(42,2)"
37 = "send(4,2)"
38 = "send(43,2)"
41 = "send(6,0)"
42 = "send(2,0)"
43 = "send(0,0)"
44 = "send(10,0)"
45 = "send(6,2)"
46 = "send(2,2)"
47 = "send(0,2)"
48 = "send(10,2)"
# 61 = "no address"
# 62 = "no address"
# 100 = "no address"
# 101 = "no address"
# 102 = "no address"
[midi_mapping_note_off]
# 0 = "init"
# 1 = "monitor(on)"
# 2 = "monitor(off)"
# 3 = "send(31,4)"
# 4 = "mute(0)"
# 5 = "mute(2)"
# 6 = "unmute(0)"
# 7 = "unmute(2)"
# 8 = "print"